Repository lablup/backend.ai-agent, pull requests merged in 2020-10, with the labels that each got.

#236 fix: regression of task-log filename normalization due to new env-var
  changes/236.fix
  src/ai/backend/kernel/base.py
Labels: bot:chronographer:provided

#237 setup: Update krunner versions
  changes/237.fix
  setup.cfg
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/resources.py
  src/ai/backend/agent/watcher.py
Labels: bot:chronographer:provided, enhancement

#238 fix: update dependencies (aiohttp~=3.7.0, trafaret~=2.1)
  changes/238.fix
  setup.cfg
Labels: bot:chronographer:provided

#230 Feature/shutdown service apps
  changes/230.feature
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/docker/kernel.py
  src/ai/backend/agent/kernel.py
  src/ai/backend/agent/server.py
  src/ai/backend/kernel/base.py
  tests/test_resources.py
Labels: agent, bot:chronographer:provided, enhancement, kernel-runner
