Repository lablup/backend.ai-agent, pull requests merged in 2020-09, with the labels that each got.

#229 fix: add context parameter for init methods of intrinsic accelerators
  changes/229.fix
  src/ai/backend/agent/docker/intrinsic.py
Labels: bot:chronographer:provided, bug

#231 fix: Use the storage-proxy provided mount path
  changes/231.fix
  src/ai/backend/agent/docker/agent.py
Labels: bot:chronographer:provided

#233 Skip vfolder config checks if the etcd's mount path is not specified
  changes/233.fix
  src/ai/backend/agent/server.py
Labels: bot:chronographer:provided

#234 Add config option to allow skipping of running manager detection
  changes/234.feature
  config/sample.toml
  src/ai/backend/agent/config.py
  src/ai/backend/agent/server.py
Labels: bot:chronographer:provided

#232 Add support for dotfiles of domains and groups
  changes/232.fix
  src/ai/backend/agent/docker/agent.py
Labels: bot:chronographer:provided, enhancement

#228 Even allocation of GPU for FractionAllocMap
  changes/228.feature
  src/ai/backend/agent/resources.py
  tests/test_alloc_map.py
Labels: bot:chronographer:provided

#235 Refactor service port parsing function to backend.ai-common
  changes/235.fix
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/utils.py
  tests/test_utils.py
Labels: bot:chronographer:provided

#164 Implement basic multi container session
  changes/164.feature
  config/sample.toml
  setup.cfg
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/config.py
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/kernel.py
  src/ai/backend/agent/resources.py
  src/ai/backend/agent/server.py
  src/ai/backend/kernel/base.py
  src/ai/backend/kernel/intrinsic.py
  tests/test_server.py
Labels: bot:chronographer:provided
