Repository lablup/backend.ai-agent, pull requests merged in 2020-03, with the labels that each got.

#187 Better container lifecycle management using queues
  setup.cfg
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/docker/intrinsic.py
  src/ai/backend/agent/docker/kernel.py
  src/ai/backend/agent/kernel.py
  src/ai/backend/agent/resources.py
  src/ai/backend/agent/server.py
  src/ai/backend/agent/types.py
  src/ai/backend/kernel/python/drawing/encoding.py
Labels: blocker, bug, enhancement

#188 Bugfix - typo in updating agent's image list
  src/ai/backend/agent/agent.py
Labels: bug

#191 fix: parameter to match with code-server 2.X (backend.ai#171)
  src/ai/backend/kernel/python/__init__.py
Labels: enhancement

#194 Promote vscode as intrinsic service and improve service-port handling
  src/ai/backend/kernel/base.py
  src/ai/backend/kernel/intrinsic.py
  src/ai/backend/kernel/python/__init__.py
Labels: agent, enhancement, kernel-runner
