Repository lablup/backend.ai-agent, pull requests merged in 2020-04, with the labels that each got.

#195 feat: add exception list for 22 / 80 / 443 ports (lablup/backend.ai#175)
  src/ai/backend/agent/utils.py
Labels: enhancement

#196 Adopt towncrier for changelog management
  CHANGELOG.md
  HISTORY.rst
  changes/0.breaking
  changes/0.feature
  changes/0.fix
  changes/157.feature
  changes/161.feature
  changes/162.feature
  changes/165.feature
  changes/167.feature
  changes/189.deprecation
  changes/189.feature
  changes/189.fix
  changes/189.misc
  changes/196.misc
  changes/template.md
  pyproject.toml
  setup.cfg
Labels: bot:chronographer:provided

#186 Make scratch access asynchronous
  changes/186.fix
  setup.cfg
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/docker/intrinsic.py
  src/ai/backend/agent/docker/kernel.py
  src/ai/backend/agent/kernel.py
  src/ai/backend/agent/proxy.py
  src/ai/backend/agent/server.py
  src/ai/backend/agent/utils.py
  src/ai/backend/kernel/base.py
  src/ai/backend/runner/entrypoint.sh
  src/ai/backend/runner/extract_dotfiles.py
Labels: bot:chronographer:provided

#197 fix: Make krunner service-def parsers consistent with docs
  changes/197.fix
  src/ai/backend/kernel/service.py
  src/ai/backend/kernel/service_actions.py
Labels: bot:chronographer:provided

#174 backport: Place bootstrap script upon session creation
  src/ai/backend/agent/docker/agent.py
Labels: enhancement

#190 Mark kernel started after bootstrap script
  changes/190.feature
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/runner/entrypoint.sh
Labels: bot:chronographer:provided, enhancement, kernel-runner

#201 repo: Adopt towncrier for changelog mgmt
  CHANGELOG.md
  HISTORY.md
  changes/201.misc
  changes/template.md
  pyproject.toml
  setup.cfg
Labels: bot:chronographer:provided

#199 fix: Convert unhandled error to a serializable exception form
  changes/199.fix
  src/ai/backend/agent/server.py
Labels: bot:chronographer:provided

#200 fix: Alway force-delete the container
  changes/200.fix
  src/ai/backend/agent/docker/agent.py
Labels: bot:chronographer:provided

#202 fix: Keep the docker event log processor running
  changes/202.fix
  src/ai/backend/agent/docker/agent.py
Labels: bot:chronographer:provided

#203 fix: Use destroy() of ZeroMQ context objects instead of term()
  changes/203.fix
  src/ai/backend/agent/kernel.py
  tests/test_stats.py
Labels: bot:chronographer:provided

#204 fix: Delete volumes with when deleting containers
  changes/204.fix
  src/ai/backend/agent/docker/agent.py
Labels: bot:chronographer:provided

#205 fix: Check closing of zmq sockets in code runner
  changes/205.fix
  src/ai/backend/agent/kernel.py
Labels: bot:chronographer:provided

#206 fix: Introduce "already-terminated" reason for kernel_terminated events
  changes/206.fix
  src/ai/backend/agent/agent.py
Labels: bot:chronographer:provided

#207 fix: Fortify exception handling in container lifecycle processor
  changes/207.fix
  src/ai/backend/agent/agent.py
Labels: bot:chronographer:provided
