Repository lablup/backend.ai-agent, pull requests merged in 2021-01, with the labels that each got.

#260 fix: compile scp / sftp-server with proper prefix
  changes/260.fix
  scripts/build-sftpserver.sh
  src/ai/backend/runner/scp.alpine3.8.x86_64.bin
  src/ai/backend/runner/scp.centos7.6.x86_64.bin
  src/ai/backend/runner/scp.ubuntu16.04.x86_64.bin
  src/ai/backend/runner/scp.ubuntu18.04.x86_64.bin
  src/ai/backend/runner/scp.ubuntu20.04.x86_64.bin
  src/ai/backend/runner/sftp-server.alpine3.8.x86_64.bin
  src/ai/backend/runner/sftp-server.centos7.6.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu16.04.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu18.04.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu20.04.x86_64.bin
Labels: bug

#261 feat: Allow env customization by individual images
  changes/261.feature
  src/ai/backend/runner/entrypoint.sh
Labels: enhancement, kernel-runner

#262 Fix event races for kernel creation (#256, #254)
  changes/256.fix
  changes/262.breaking
  src/ai/backend/agent/agent.py
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/server.py
Labels: bug

#263 fix: Improve shutdown stability using aiotools v1.2
  .github/workflows/timeline-check.yml
  changes/263.fix
  setup.cfg
  src/ai/backend/agent/server.py
Labels: bug

#259 fix: Use agent ID for socket relay container name
  changes/259.feature
  src/ai/backend/agent/docker/agent.py
  src/ai/backend/agent/docker/utils.py
Labels: enhancement

#264 fix: Improve handling of container initialization failure
  changes/264.fix
  src/ai/backend/agent/agent.py
Labels: bug

#265 fix: SSHJ compatibility issue while sending large files
  changes/265.fix
  scripts/build-sftpserver.sh
  src/ai/backend/runner/scp.alpine3.8.x86_64.bin
  src/ai/backend/runner/scp.centos7.6.x86_64.bin
  src/ai/backend/runner/scp.ubuntu16.04.x86_64.bin
  src/ai/backend/runner/scp.ubuntu18.04.x86_64.bin
  src/ai/backend/runner/scp.ubuntu20.04.x86_64.bin
  src/ai/backend/runner/sftp-server.alpine3.8.x86_64.bin
  src/ai/backend/runner/sftp-server.centos7.6.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu16.04.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu18.04.x86_64.bin
  src/ai/backend/runner/sftp-server.ubuntu20.04.x86_64.bin
Labels: bug, kernel-runner

#267 setup: Update dependencies
  changes/267.fix
  setup.cfg
  src/ai/backend/agent/server.py
Labels: agent, enhancement

#268 fix: Ensure init_done.set() when sshd initialization fails
  changes/268.fix
  src/ai/backend/kernel/base.py
Labels: bug, kernel-runner
